### ISSUE TITLE
Getting started causes Error: Package subpath './lib/sidebars/generator'

### ISSUE THREAD

**Issue by skoshx** [cloud-annotations/docusaurus-openapi#160]
Started by trying to bootstrap a normal project:

```bash
npx create-docusaurus-openapi pizza
cd pizza
npm start
```
After which i get this error:
```javascript
[ERROR] Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/sidebars/generator' is not defined by "exports" in /Users/rasmus/Desktop/DEV/Work/pizza/node_modules/@docusaurus/plugin-content-docs/package.json
    at new NodeError (internal/errors.js:322:7)
    at throwExportsNotFound (internal/modules/esm/resolve.js:322:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:545:3)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/rasmus/Desktop/DEV/Work/pizza/node_modules/docusaurus-plugin-openapi/lib/sidebars/index.js:14:21)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)

```

`node --version`: v14.18.1
`npm --version`: 6.14.15

By the way, absolutely love this project! Would like to create a pull request to fix this but at the moment I have absolutely no clue how to get around this.

**Comment by bourdakos1** [comment]
Hey @skoshx! Thanks for opening an issue, I'll take a look :)

**Comment by bourdakos1** [comment]
It seems like Docusaurus `2.0.0-beta.15` has broken some things. Even though we pin the version to `2.0.0-beta.14` it ends up also installing newer versions due to Docusaurus depending on itself. As a temporary workaround, you can add this to your `package.json`:

```json
"resolutions": {
    "@docusaurus/core": "2.0.0-beta.14",
    "@docusaurus/preset-classic": "2.0.0-beta.14",
    "@docusaurus/mdx-loader": "2.0.0-beta.14",
    "@docusaurus/plugin-content-docs": "2.0.0-beta.14",
    "@docusaurus/types": "2.0.0-beta.14",
    "@docusaurus/utils-validation": "2.0.0-beta.14",
    "@docusaurus/utils": "2.0.0-beta.14"
},
```

**Comment by skoshx** [comment]
@bourdakos1 Hello, thanks for the quick reply! Your workaround works perfectly! Thanks :) Should I close this issue or keep it open to reference when a possible fix is available?

**Comment by bourdakos1** [comment]
Let’s leave this open, thanks 😊

**Comment by Misotech** [comment]
Help. Solution above doesn't work for me

> my-website@0.0.0 start
> docusaurus start


   ╭────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                        │
   │                     Update available 2.0.0-beta.14 → 2.0.0-beta.15                     │
   │                                                                                        │
   │   To upgrade Docusaurus packages with the latest version, run the following command:   │
   │                            `npm i @docusaurus/core@latest`                             │
   │                                                                                        │
   ╰────────────────────────────────────────────────────────────────────────────────────────╯

[INFO] Starting the development server...
[ERROR] Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/sidebars/generator' is not defined by "exports" in /Users/ilya/my-website/node_modules/@docusaurus/plugin-content-docs/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:453:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:729:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/ilya/my-website/node_modules/docusaurus-plugin-openapi/lib/sidebars/index.js:14:21)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)

**Comment by skoshx** [comment]
@Misotech Are you using `yarn` or `npm`? I don't know if `npm` supports `resolutions` in package.json

**Comment by bourdakos1** [comment]
Try deleting yarn.lock and node_modules

**Comment by Misotech** [comment]
@bourdakos1 don't work it

**Comment by bourdakos1** [comment]
Can you upload a copy of your package.json and yarn.lock?

**Comment by skoshx** [comment]
@Misotech You have to help us help you, you gotta give us more to go on than "don't work it". What steps did you do exactly to come to your error? What happens if you reproduce exactly your steps? What is your node version, what is your yarn version?

My steps to get it to work:
```bash
$ npx create-docusaurus-openapi pizza
$ cd pizza
$ # Here add `resolutions` to package.json, then:
$ yarn start
```

**Comment by Misotech** [comment]
My steps:

$ npx create-docusaurus-openapi pizza
$ cd pizza
$ # Here add `resolutions` to package.json, then:
$ yarn start


Node version 16.14.0
Yarn version 1.22.17

Archive with package.json and yarn.lock

[Archive.zip](https://github.com/cloud-annotations/docusaurus-openapi/files/8054209/Archive.zip)

**Comment by bourdakos1** [comment]
You should have to run “yarn install” after adding the resolutions. I won’t have access to a computer this weekend, so I can take a closer look on Monday

**Comment by Misotech** [comment]
@bourdakos1 Thanks! This is work

**Comment by bourdakos1** [comment]
Have you tried the workaround?

**Comment by skoshx** [comment]
@bourdakos1 Workaround still works, but I can't seem to get the docusaurus to look exatly as it does on [https://docusaurus-openapi.netlify.app/petstore/add-a-new-pet-to-the-store](https://docusaurus-openapi.netlify.app). I think the new look on the deployed netflify looks amazing but I don't understand how to get the same look :smile:

**Comment by bourdakos1** [comment]
Oh yea, thanks :) I added some custom css here to make it look different: https://github.com/cloud-annotations/docusaurus-openapi/blob/main/demo/src/css/custom.css

**Comment by skoshx** [comment]
Oh ok, thanks a lot! Will defenitely steal it :wink: Btw, I was thinking of adding a feature where the `openapiPath` could be an URL, and the OpenAPI spec would get fetched from there instead of disk, are there any problems you could think of for a feature like that or should I get on it and submit a PR?

**Comment by bourdakos1** [comment]
The only issue is if you expect the site to change if the spec at the given URL changes. Since the docs are statically generated, it would only fetch the spec from the URL when the production build is run.

If that’s the expected behavior, go ahead and submit a PR :)

**Comment by skoshx** [comment]
Yeah, figured as much from reading the code. Since we have an API where the OpenAPI definitions are subject to change at this time, there would have to be some way of regenerating the docs, so have to think more about this…

By the way, do you know the root cause of this issue? Is this just an upstream docusaurus issue and there is no fix for it? I don't want to sound archaic but would be nice for `docusaurus-openapi` to work with npm aswell :D

**Comment by YanDevDe** [comment]
I'm also having the same issue, I'm currently on beta.18 for docusaurus and I'm getting the error of `ERR_PACKAGE_PATH_NOT_EXPORTED`.
Adding the `resolutions` to package.json (and then removing node_modules / yarn.lock - yarn install) resulted in a different error:

```
[ERROR] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
```

So it is kinda deadend for me it appears 🥲 

Here is my package.json:

```
{
  "name": "example-docs",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "docusaurus": "docusaurus",
    "start": "docusaurus start",
    "build": "docusaurus build",
    "swizzle": "docusaurus swizzle",
    "deploy": "docusaurus deploy",
    "clear": "docusaurus clear",
    "serve": "docusaurus serve",
    "write-translations": "docusaurus write-translations",
    "write-heading-ids": "docusaurus write-heading-ids"
  },
  "dependencies": {
    "@docusaurus/core": "^2.0.0-beta.18",
    "@docusaurus/plugin-content-docs": "^2.0.0-beta.18",
    "@docusaurus/preset-classic": "^2.0.0-beta.18",
    "@mdx-js/react": "^1.6.21",
    "@svgr/webpack": "^5.5.0",
    "clsx": "^1.1.1",
    "docusaurus-plugin-openapi": "^0.5.0",
    "file-loader": "^6.2.0",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "url-loader": "^4.1.1"
  },
  "resolutions": {
    "@docusaurus/core": "2.0.0-beta.14",
    "@docusaurus/preset-classic": "2.0.0-beta.14",
    "@docusaurus/mdx-loader": "2.0.0-beta.14",
    "@docusaurus/plugin-content-docs": "2.0.0-beta.14",
    "@docusaurus/types": "2.0.0-beta.14",
    "@docusaurus/utils-validation": "2.0.0-beta.14",
    "@docusaurus/utils": "2.0.0-beta.14"
  },
  "browserslist": {
    "production": [
      ">0.5%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "axios": "^0.21.2"
  }
}
```

**Comment by timelesssys** [comment]
I'm seeing the same happening as @YanDevDe. 
Running `yarn run docusaurus --help` gives more information for where the error is located:
```
yarn run v1.22.15
$ docusaurus --help
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (internal/errors.js:322:7)
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:1148:7)
    at getTranslationsDirPath (/home/pi/git/TC-SP-API-Docs/node_modules/@docusaurus/core/lib/server/translations/translations.js:84:50)
    at getTranslationsLocaleDirPath (/home/pi/git/TC-SP-API-Docs/node_modules/@docusaurus/core/lib/server/translations/translations.js:87:32)
    at getCodeTranslationsFilePath (/home/pi/git/TC-SP-API-Docs/node_modules/@docusaurus/core/lib/server/translations/translations.js:91:32)
    at readCodeTranslationFileContent (/home/pi/git/TC-SP-API-Docs/node_modules/@docusaurus/core/lib/server/translations/translations.js:94:39)
    at loadContext (/home/pi/git/TC-SP-API-Docs/node_modules/@docusaurus/core/lib/server/index.js:58:97)
    at async externalCommand (/home/pi/git/TC-SP-API-Docs/node_modules/@docusaurus/core/lib/commands/external.js:13:21)
    at async file:///home/pi/git/TC-SP-API-Docs/node_modules/@docusaurus/core/bin/docusaurus.mjs:267:3 {
  code: 'ERR_INVALID_ARG_TYPE'
}
error Command failed with exit code 1.
```

**Comment by prakashiit** [comment]
Hi! I also faced the same issue related to `Error: Package subpath './lib/sidebars/generator'` but applying the given solution caused me to run into a different issue.

**Error faced**:
```

> ma-website@0.0.0 start C:\Users\Prakash\Desktop\Repositories\pocs\docusaurus\ma-website
> docusaurus start


   ╭────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                        │
   │                     Update available 2.0.0-beta.14 → 2.0.0-beta.20                     │
   │                                                                                        │
   │   To upgrade Docusaurus packages with the latest version, run the following command:   │
   │                         `yarn upgrade @docusaurus/core@latest`                         │
   │                                                                                        │
   ╰────────────────────────────────────────────────────────────────────────────────────────╯

[INFO] Starting the development server...
[SUCCESS] Docusaurus website is running at http://localhost:3000/.
(node:25964) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
(Use `node --trace-deprecation ...` to show where the warning was created)

✖ Client
  Compiled with some errors in 7.11s



Module not found: Error: Can't resolve 'url' in 'C:\Users\Prakash\Desktop\Repositories\pocs\docusaurus\ma-website\node_modules\postman-code-generators\codegens\http\node_modules\postman-url-encoder\encoder'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "url": require.resolve("url/") }'
        - install 'url'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "url": false }
```
**Setup Steps:**
```
yarn create docusaurus-openapi ma-website
# Update package.json with resolutions mentioned above
yarn install
yarn start
```
**Installed versions:**
node: v14.16.1
yarn: 1.22.15
npm: 6.14.12


I'm not able to understand how I can start solving this. Any help would be appreciated. Thanks!

**Comment by zia-inceptus** [comment]
The same issue is happening on Docusaurus beta.21.

**Comment by baptisteArno** [comment]
@bourdakos1 any indication on how to potentially fix the issue for the latest version of docusaurus? I'd like to create a pull request

**Comment by baptisteArno** [comment]
Even after setting the resolutions, deleting node_modules and yarn.lock, it still displays `"@docusaurus/core@2.0.0-beta.21"` in yarn.lock. and the error happens ...

**Comment by bourdakos1** [comment]
Docusaurus made a couple functions that we use private, so you can either make a pull request to Docusaurus making them public or make a pull request here reimplementing the logic of the private functions

**Comment by DaxlinksG** [comment]
[ERROR] TypeError: (0 , utils_1.getDataFilePath) is not a function
    at Object.pluginContentBlog [as plugin] (C:\Users\TEMITAYO\Desktop\zeehDocs\node_modules\@docusaurus\plugin-content-blog\lib\index.js:39:66)
    
    After adding the resolution, This is the new error that gets generated, How to fix this please?
