### ISSUE TITLE
CORS?

### ISSUE THREAD

**Issue by kevinelliott** [cloud-annotations/docusaurus-openapi#168]
I am trying to allow users to interact with the OpenAPI definition, but when Execute is clicked there are CORS errors. How do you make this work?

**Comment by skoshx** [comment]
@kevinelliott 

Does your server send cors headers when a request is made to it? If not, then obviously that is the problem. 

Since `docusaurus-openapi` is client side (in the browser) I strongly suspect the reason to your CORS errors lies in your server itself, not a problem with this package.

**Comment by kevinelliott** [comment]
I do not use CORS with my API server at this time.

**Comment by kevinelliott** [comment]
```
Access to fetch at 'http://localhost:8080/messages/12312' from origin 'http://localhost:3001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by bourdakos1** [comment]
You need to set up CORS on your server

or if this is in dev mode (not a production build) you can use the dev server proxy to forward requests to your server, bypassing CORS
