### ISSUE TITLE
How to change `path` of Docusaurus OpenAPI?

### ISSUE THREAD

**Issue by skoshx** [cloud-annotations/docusaurus-openapi#171]
The docs state that `path can be configured in docusaurus.config.js`, however it doesn't mention at all where to put it. The top level doesn't work.
```
/openapi.json - The default OpenAPI defination that will be served (path can be configured in docusaurus.config.js).
```

I have absolutely no clue where to put the options so that they would get passed on to the `docusaurus-plugin-openapi`....

**Comment by bourdakos1** [comment]
Checkout the demo, it uses a custom path

**Comment by skoshx** [comment]
Oh my bad! Didn't notice, thanks a lot!
