### ISSUE TITLE
How to utilise proxy?

### ISSUE THREAD

**Issue by ochhii1337** [cloud-annotations/docusaurus-openapi#180]
Hi - Firstly thanks, I like what you have built here!

I have my docs running on a separate domain to the api. How can I change the url here?

![image](https://user-images.githubusercontent.com/14752426/169559114-9019c066-d342-41f5-ac32-e67a2f11f1be.png)

I have tried to replicate what is in the demo:

```
presets: [
    [
      'docusaurus-preset-openapi',
      /** @type {import('docusaurus-preset-openapi').Options} */
      ({
        docs: {
          routeBasePath: '/',
          sidebarPath: require.resolve('./sidebars.js'),
          // Please change this to your repo.
          // editUrl: 'https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/',
        },
        blog: false,
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
        proxy: {
          "/api": {
            target: 'https://my-api-site',
            pathRewrite: { "^/api": "" }
          }
        }
      }),
    ],
  ],
```

But still 'Execute' the requests try to call `http://localhost:3000/health`. How can I redirect requests to `https://my-api-site/health`?

**Comment by bourdakos1** [comment]
The code you have here should redirect requests from `http://localhost:3000/api/health` to `https://my-api-site/health`
