### ISSUE TITLE
Loading failed for local openapi json file

### ISSUE THREAD

**Issue by yzhe819** [cloud-annotations/docusaurus-openapi#190]
When I update my project from the old version "0.4.0" to the latest version "0.6.0", I can't start the project.
Below is a screenshot of the error.

<details>
<summary>screenshot</summary>

![图片](https://user-images.githubusercontent.com/68207314/176387508-c5487f37-1b6c-479b-8bc6-00e09c2769e6.png)
</details>

## How to reproduce
I started from the template one
```
npx create-docusaurus-openapi docusaurus-openapi-example
```
Then update the package
```
yarn upgrade docusaurus-preset-openapi --latest
```
Also, add `url` for fixing url issue
```
yarn add url
```
Then, I start the project
```
cd docusaurus-openapi-example
yarn start
```
Check the above screenshot.

The following is my package.json
<details>
<summary>package.json</summary>

```
{
  "name": "docusaurus-openapi-example",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "@docusaurus/core": "2.0.0-beta.21",
    "@mdx-js/react": "^1.6.21",
    "clsx": "^1.1.1",
    "docusaurus-preset-openapi": "0.6.0",
    "prism-react-renderer": "^1.2.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "url": "^0.11.0"
  },
  "scripts": {
    "docusaurus": "docusaurus",
    "start": "docusaurus start",
    "build": "docusaurus build",
    "swizzle": "docusaurus swizzle",
    "deploy": "docusaurus deploy",
    "clear": "docusaurus clear",
    "serve": "docusaurus serve",
    "write-translations": "docusaurus write-translations",
    "write-heading-ids": "docusaurus write-heading-ids"
  },
  "browserslist": {
    "production": [
      ">0.5%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```
</details>

## Comment
Please let me know if I make any mistakes in the initialization of the project.

PS: Maybe the template example also needs a version update💖

**Comment by ianberryman** [comment]
@yzhe819 I have the same issue on Windows. The absolute path of the api file is recognized as a valid URL (see https://github.com/nodejs/node/issues/34765). [`utils.isUrl()`](https://github.com/cloud-annotations/docusaurus-openapi/blob/main/packages/docusaurus-plugin-openapi/src/util.ts) needs to be changed to support absolute paths.

**Comment by yzhe819** [comment]
@ianberryman Thanks for your advice. I use regular expressions instead of URL to avoid this platform issue. Just waiting for code review. Feel free to take a look.

**Comment by ianberryman** [comment]
@yzhe819 Nice, I'm going to pull your fork and use it until the PR is merged
