### ISSUE TITLE
MDX content in params is displayed in form elements

### ISSUE THREAD

**Issue by chris48s** [cloud-annotations/docusaurus-openapi#257]
Here's a screenshot showing the issue:

![Screenshot at 2023-07-23 19-11-48](https://github.com/cloud-annotations/docusaurus-openapi/assets/6025893/e1e49165-0584-47dd-8e65-2513860dce18)

Ideally, the tags would be stripped in this context, leaving only the plain text.

I'd be happy to work on this issue. I'm not quite sure how to approach it though.

One option would be to just treat the placeholder as a string `placeholder.replace(/(<([^>]+)>)/gi, "");` would be enough to remove HTML tags. Maybe markdown is the lesser evil. Crude but simple.

It seems like it should be possible to use some of the existing MDX/remark tooling that this lib and docusaurus already pull in to render the content of the string into a tree structure we can traverse and then extract just the text nodes. That seems like a more robust approach, but I'm not sure that [MDX](https://mdxjs.com/) exposes a suitable API for that though.

**Comment by bourdakos1** [comment]
It looks like marked has a text renderer so maybe we could try using that? https://github.com/markedjs/marked/blob/master/src/TextRenderer.js
