### ISSUE TITLE
This page crashed - URI malformed - When inserting win10 keyboard emoji on api field

### ISSUE THREAD

**Issue by jNullj** [cloud-annotations/docusaurus-openapi#260]
This was first detected in badges/shields#9519, Read more there
I can reproduce this on [docusaurus-openapi.netlify.app](https://docusaurus-openapi.netlify.app/)
1. Go to https://docusaurus-openapi.netlify.app/petstore/get-user-by-user-name/
2. Select the `username` text input field
3. Open win10 on screen keyboard (the one that pop-ups from bellow, not the old win7 version)
4. Select an emoji
5. Get page crash with URI malformed

**Comment by jNullj** [comment]
More findings:
I see a diff with events data when using windows on-screen keyboard and emoji shortcut (winkey+.)
With on-screen keyboard when the issue appears:
![image](https://github.com/cloud-annotations/docusaurus-openapi/assets/15849761/168592fe-be72-47a3-a087-1a7b776596b5)
With the emoji picker (win+.) when there is no issue:
![image](https://github.com/cloud-annotations/docusaurus-openapi/assets/15849761/35a253a4-3d16-4d86-a157-2089f66b9b2e)

**Comment by jNullj** [comment]
Found the bug!
![image](https://github.com/cloud-annotations/docusaurus-openapi/assets/15849761/6bf099d6-2d2f-48f4-a2d2-41f03feabca6)
We are using  `encodeURIComponent` to convert to a URI in the api call, but `encodeURIComponent` does not work with the unicode format '\uD83C' that the keyboard outputs insted of the emoji itself.

This can be found in https://github.com/cloud-annotations/docusaurus-openapi/blob/main/packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/buildPostmanRequest.ts

I can make a pull request fixing this

**Comment by jNullj** [comment]
Was too quick, this is not a valid unicode, i need to keep debugging

**Comment by jNullj** [comment]
Ok new insight, this is probebly related to onInput event.
It appears that when i type using onInput the emoji start as non-exitsting unicode like \uD83C then the input continues and completes it into the pizza emoji.
But our code tries to use `encodeURIComponent` in this middle state where only partial emoji was registered by onInput

**Comment by jNullj** [comment]
Confirmed using this textbox on github. I asked it to print to console the onInput event and from 1 emoji input using the keyboard i get 2 onInput events
![image](https://github.com/cloud-annotations/docusaurus-openapi/assets/15849761/9d9f3873-9d3d-49d8-9c92-5ab6c60ff8b9)

**Comment by bourdakos1** [comment]
Good find! Thanks for looking into this :)
