### ISSUE TITLE
Docusaurus 3.0 support

### ISSUE THREAD

**Issue by techwritermat** [cloud-annotations/docusaurus-openapi#264]
Adding `docusaurus-preset-openapi` to my package.json adds a dependency to docusaurus core v2.4.3. and my entire Docusaurus 3.0 project doesn't build. Are there plans to have this preset work with the Docusaurus 3.0 core components instead of Docusaurus 2.4.3?

**Comment by Devon-White** [comment]
Hello, I am also running into the same issue and was wondering if there are any plans to support this with v3.

**Comment by bourdakos1** [comment]
It shouldn’t be too difficult to upgrade this project to v3. There’s migration instructions here: https://docusaurus.io/docs/migration/v3

if someone is interested in making a pull request

**Comment by techwritermat** [comment]
Thank you so much for this. Testing it now!

**Comment by techwritermat** [comment]
Created release PR: https://github.com/cloud-annotations/docusaurus-openapi/pull/268
