### ISSUE TITLE
Are you compatible with Docusaurus 3.x.x?

### ISSUE THREAD

**Issue by monica-m-ps** [cloud-annotations/docusaurus-openapi#281]
Hello. I'm looking for an opensource plugin that works with Docusaurus 3.x.x. I've searched online and they are still in progress. 
Do you have plans to enable compatibility with 3.x.x anytime soon? Thanks

**Comment by bourdakos1** [comment]
Yes, we are compatible with Docusaurus v3 starting with v0.7.0 😁
