### ISSUE TITLE
Modify Label in sidebar (autogenerated)

### ISSUE THREAD

**Issue by Pratosh22** [cloud-annotations/docusaurus-openapi#286]
1. Is there a way to modify the sidebar labels autogenerated from the OpenAPI? For example in my case the OpenAPI returns with "audit_logs" i want it to be rendered as Audit Logs in the sidebar.

**Comment by bourdakos1** [comment]
Can you share the relevant snippet of your OpenAPI spec?

**Comment by Pratosh22** [comment]
<img width="1033" alt="Screenshot 2024-04-08 at 6 16 45 PM" src="https://github.com/cloud-annotations/docusaurus-openapi/assets/76246084/571a4aae-91a6-4fea-aaa4-81553181b63e">
This is how it is rendered : 
<img width="300" alt="Screenshot 2024-04-08 at 6 17 44 PM" src="https://github.com/cloud-annotations/docusaurus-openapi/assets/76246084/da417489-8d08-44e9-b80e-0fb9fe36a3f9">

**Comment by bourdakos1** [comment]
You should be able to add `x-displayName: Audit Logs`  to the `audit_logs` tag. You can find an example here: https://github.com/cloud-annotations/docusaurus-openapi/blob/0d2e0ec7faeb23cbcc62e1a59c258a2cc780b00f/demo/examples/petstore.yaml#L62

**Comment by Pratosh22** [comment]
Thanks,That did it!
