### ISSUE TITLE
remove axios dependency

### ISSUE THREAD

**Issue by benmccann** [cloud-annotations/docusaurus-openapi#287]
axios is barely used and so could be replaced by Node's built-in `fetch` without too much effort

Removing axios would reduce the number of dependencies. We are using the oazapfts implementation of openapi, so wouldn't have axios used if not for this library pulling it in

The version of axios currently being used has security vulnerabilities, the change would also address that

**Comment by bourdakos1** [comment]
Would be happy to approve a PR that swaps axios for fetch :)
